/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('pokemon').del()
  await knex('pokemon').insert([
    {entry_no: 1, name_en: 'Bulbasaur', category: 'seed Pokémon' },
    {entry_no: 2, name_en: 'Ivysaur', category: 'seed Pokémon' },
    {entry_no: 3, name_en: 'Venusaur', category: 'seed Pokémon' },
    {entry_no: 4, name_en: 'Charmander', category: 'lizard Pokémon' },
    {entry_no: 5, name_en: 'Charmeleon', category: 'flame Pokémon' },
    {entry_no: 6, name_en: 'Charizard', category: 'flame Pokémon' },
    {entry_no: 7, name_en: 'Squirtle', category: 'tiny turtle Pokémon' },
    {entry_no: 8, name_en: 'Wartortle', category: 'turtle Pokémon' },
    {entry_no: 9, name_en: 'Blastoise', category: 'shellfish Pokémon' },
    {entry_no: 10, name_en: 'Caterpie', category: 'worm Pokémon' },
    {entry_no: 11, name_en: 'Metapod', category: 'cocoon Pokémon' },
    {entry_no: 12, name_en: 'Butterfree', category: 'butterfly Pokémon' },
    {entry_no: 13, name_en: 'Weedle', category: 'hairy bug Pokémon' },
    {entry_no: 14, name_en: 'Kakuna', category: 'cocoon Pokémon' },
    {entry_no: 15, name_en: 'Beedrill', category: 'poison bee Pokémon' },
    {entry_no: 16, name_en: 'Pidgey', category: 'tiny bird Pokémon' },
    {entry_no: 17, name_en: 'Pidgeotto', category: 'bird Pokémon' },
    {entry_no: 18, name_en: 'Pidgeot', category: 'bird Pokémon' },
    {entry_no: 19, name_en: 'Rattata', category: 'mouse Pokémon' },
    {entry_no: 20, name_en: 'Raticate', category: 'mouse Pokémon' },
    {entry_no: 21, name_en: 'Spearow', category: 'tiny bird Pokémon' },
    {entry_no: 22, name_en: 'Fearow', category: 'beak Pokémon' },
    {entry_no: 23, name_en: 'Ekans', category: 'snake Pokémon' },
    {entry_no: 24, name_en: 'Arbok', category: 'cobra Pokémon' },
    {entry_no: 25, name_en: 'Pikachu', category: 'mouse Pokémon' },
    {entry_no: 26, name_en: 'Raichu', category: 'mouse Pokémon' },
    {entry_no: 27, name_en: 'Sandshrew', category: 'mouse Pokémon' },
    {entry_no: 28, name_en: 'Sandslash', category: 'mouse Pokémon' },
    {entry_no: 29, name_en: 'Nidoran-f', category: 'poison pin Pokémon' },
    {entry_no: 30, name_en: 'Nidorina', category: 'poison pin Pokémon' },
    {entry_no: 31, name_en: 'Nidoqueen', category: 'drill Pokémon' },
    {entry_no: 32, name_en: 'Nidoran-m', category: 'poison pin Pokémon' },
    {entry_no: 33, name_en: 'Nidorino', category: 'poison pin Pokémon' },
    {entry_no: 34, name_en: 'Nidoking', category: 'drill Pokémon' },
    {entry_no: 35, name_en: 'Clefairy', category: 'fairy Pokémon' },
    {entry_no: 36, name_en: 'Clefable', category: 'fairy Pokémon' },
    {entry_no: 37, name_en: 'Vulpix', category: 'fox Pokémon' },
    {entry_no: 38, name_en: 'Ninetales', category: 'fox Pokémon' },
    {entry_no: 39, name_en: 'Jigglypuff', category: 'balloon Pokémon' },
    {entry_no: 40, name_en: 'Wigglytuff', category: 'balloon Pokémon' },
    {entry_no: 41, name_en: 'Zubat', category: 'bat Pokémon' },
    {entry_no: 42, name_en: 'Golbat', category: 'bat Pokémon' },
    {entry_no: 43, name_en: 'Oddish', category: 'weed Pokémon' },
    {entry_no: 44, name_en: 'Gloom', category: 'weed Pokémon' },
    {entry_no: 45, name_en: 'Vileplume', category: 'flower Pokémon' },
    {entry_no: 46, name_en: 'Paras', category: 'mushroom Pokémon' },
    {entry_no: 47, name_en: 'Parasect', category: 'mushroom Pokémon' },
    {entry_no: 48, name_en: 'Venonat', category: 'insect Pokémon' },
    {entry_no: 49, name_en: 'Venomoth', category: 'poison moth Pokémon' },
    {entry_no: 50, name_en: 'Diglett', category: 'mole Pokémon' },
    {entry_no: 51, name_en: 'Dugtrio', category: 'mole Pokémon' },
    {entry_no: 52, name_en: 'Meowth', category: 'scratch cat Pokémon' },
    {entry_no: 53, name_en: 'Persian', category: 'classy cat Pokémon' },
    {entry_no: 54, name_en: 'Psyduck', category: 'duck Pokémon' },
    {entry_no: 55, name_en: 'Golduck', category: 'duck Pokémon' },
    {entry_no: 56, name_en: 'Mankey', category: 'pig monkey Pokémon' },
    {entry_no: 57, name_en: 'Primeape', category: 'pig monkey Pokémon' },
    {entry_no: 58, name_en: 'Growlithe', category: 'puppy Pokémon' },
    {entry_no: 59, name_en: 'Arcanine', category: 'legendary Pokémon' },
    {entry_no: 60, name_en: 'Poliwag', category: 'tadpole Pokémon' },
    {entry_no: 61, name_en: 'Poliwhirl', category: 'tadpole Pokémon' },
    {entry_no: 62, name_en: 'Poliwrath', category: 'tadpole Pokémon' },
    {entry_no: 63, name_en: 'Abra', category: 'psi Pokémon' },
    {entry_no: 64, name_en: 'Kadabra', category: 'psi Pokémon' },
    {entry_no: 65, name_en: 'Alakazam', category: 'psi Pokémon' },
    {entry_no: 66, name_en: 'Machop', category: 'superpower Pokémon' },
    {entry_no: 67, name_en: 'Machoke', category: 'superpower Pokémon' },
    {entry_no: 68, name_en: 'Machamp', category: 'superpower Pokémon' },
    {entry_no: 69, name_en: 'Bellsprout', category: 'flower Pokémon' },
    {entry_no: 70, name_en: 'Weepinbell', category: 'flycatcher Pokémon' },
    {entry_no: 71, name_en: 'Victreebel', category: 'flycatcher Pokémon' },
    {entry_no: 72, name_en: 'Tentacool', category: 'jellyfish Pokémon' },
    {entry_no: 73, name_en: 'Tentacruel', category: 'jellyfish Pokémon' },
    {entry_no: 74, name_en: 'Geodude', category: 'rock Pokémon' },
    {entry_no: 75, name_en: 'Graveler', category: 'rock Pokémon' },
    {entry_no: 76, name_en: 'Golem', category: 'megaton Pokémon' },
    {entry_no: 77, name_en: 'Ponyta', category: 'fire horse Pokémon' },
    {entry_no: 78, name_en: 'Rapidash', category: 'fire horse Pokémon' },
    {entry_no: 79, name_en: 'Slowpoke', category: 'dopey Pokémon' },
    {entry_no: 80, name_en: 'Slowbro', category: 'hermit crab Pokémon' },
    {entry_no: 81, name_en: 'Magnemite', category: 'magnet Pokémon' },
    {entry_no: 82, name_en: 'Magneton', category: 'magnet Pokémon' },
    {entry_no: 83, name_en: 'Farfetchd', category: 'wild duck Pokémon' },
    {entry_no: 84, name_en: 'Doduo', category: 'twin bird Pokémon' },
    {entry_no: 85, name_en: 'Dodrio', category: 'triple bird Pokémon' },
    {entry_no: 86, name_en: 'Seel', category: 'sea lion Pokémon' },
    {entry_no: 87, name_en: 'Dewgong', category: 'sea lion Pokémon' },
    {entry_no: 88, name_en: 'Grimer', category: 'sludge Pokémon' },
    {entry_no: 89, name_en: 'Muk', category: 'sludge Pokémon' },
    {entry_no: 90, name_en: 'Shellder', category: 'bivalve Pokémon' },
    {entry_no: 91, name_en: 'Cloyster', category: 'bivalve Pokémon' },
    {entry_no: 92, name_en: 'Gastly', category: 'gas Pokémon' },
    {entry_no: 93, name_en: 'Haunter', category: 'gas Pokémon' },
    {entry_no: 94, name_en: 'Gengar', category: 'shadow Pokémon' },
    {entry_no: 95, name_en: 'Onix', category: 'rock snake Pokémon' },
    {entry_no: 96, name_en: 'Drowzee', category: 'hypnosis Pokémon' },
    {entry_no: 97, name_en: 'Hypno', category: 'hypnosis Pokémon' },
    {entry_no: 98, name_en: 'Krabby', category: 'river crab Pokémon' },
    {entry_no: 99, name_en: 'Kingler', category: 'pincer Pokémon' },
    {entry_no: 100, name_en: 'Voltorb', category: 'ball Pokémon' },
    {entry_no: 101, name_en: 'Electrode', category: 'ball Pokémon' },
    {entry_no: 102, name_en: 'Exeggcute', category: 'egg Pokémon' },
    {entry_no: 103, name_en: 'Exeggutor', category: 'coconut Pokémon' },
    {entry_no: 104, name_en: 'Cubone', category: 'lonely Pokémon' },
    {entry_no: 105, name_en: 'Marowak', category: 'bone keeper Pokémon' },
    {entry_no: 106, name_en: 'Hitmonlee', category: 'kicking Pokémon' },
    {entry_no: 107, name_en: 'Hitmonchan', category: 'punching Pokémon' },
    {entry_no: 108, name_en: 'Lickitung', category: 'licking Pokémon' },
    {entry_no: 109, name_en: 'Koffing', category: 'poison gas Pokémon' },
    {entry_no: 110, name_en: 'Weezing', category: 'poison gas Pokémon' },
    {entry_no: 111, name_en: 'Rhyhorn', category: 'spikes Pokémon' },
    {entry_no: 112, name_en: 'Rhydon', category: 'drill Pokémon' },
    {entry_no: 113, name_en: 'Chansey', category: 'egg Pokémon' },
    {entry_no: 114, name_en: 'Tangela', category: 'vine Pokémon' },
    {entry_no: 115, name_en: 'Kangaskhan', category: 'parent Pokémon' },
    {entry_no: 116, name_en: 'Horsea', category: 'dragon Pokémon' },
    {entry_no: 117, name_en: 'Seadra', category: 'dragon Pokémon' },
    {entry_no: 118, name_en: 'Goldeen', category: 'goldfish Pokémon' },
    {entry_no: 119, name_en: 'Seaking', category: 'goldfish Pokémon' },
    {entry_no: 120, name_en: 'Staryu', category: 'star shapedPokémon' },
    {entry_no: 121, name_en: 'Starmie', category: 'mysterious Pokémon' },
    {entry_no: 122, name_en: 'Mr-Mime', category: 'barrier Pokémon' },
    {entry_no: 123, name_en: 'Scyther', category: 'mantis Pokémon' },
    {entry_no: 124, name_en: 'Jynx', category: 'human shaped Pokémon' },
    {entry_no: 125, name_en: 'Electabuzz', category: 'electric Pokémon' },
    {entry_no: 126, name_en: 'Magmar', category: 'spitfire Pokémon' },
    {entry_no: 127, name_en: 'Pinsir', category: 'stag beetle Pokémon' },
    {entry_no: 128, name_en: 'Tauros', category: 'wild bull Pokémon' },
    {entry_no: 129, name_en: 'Magikarp', category: 'fish Pokémon' },
    {entry_no: 130, name_en: 'Gyarados', category: 'atrocious Pokémon' },
    {entry_no: 131, name_en: 'Lapras', category: 'transport Pokémon' },
    {entry_no: 132, name_en: 'Ditto', category: 'transform Pokémon' },
    {entry_no: 133, name_en: 'Eevee', category: 'evolution Pokémon' },
    {entry_no: 134, name_en: 'Vaporeon', category: 'bubble jet Pokémon' },
    {entry_no: 135, name_en: 'Jolteon', category: 'lightning Pokémon' },
    {entry_no: 136, name_en: 'Flareon', category: 'flame Pokémon' },
    {entry_no: 137, name_en: 'Porygon', category: 'virtual Pokémon' },
    {entry_no: 138, name_en: 'Omanyte', category: 'spiral Pokémon' },
    {entry_no: 139, name_en: 'Omastar', category: 'spiral Pokémon' },
    {entry_no: 140, name_en: 'Kabuto', category: 'shellfish Pokémon' },
    {entry_no: 141, name_en: 'Kabutops', category: 'shellfish Pokémon' },
    {entry_no: 142, name_en: 'Aerodactyl', category: 'fossil Pokémon' },
    {entry_no: 143, name_en: 'Snorlax', category: 'sleeping Pokémon' },
    {entry_no: 144, name_en: 'Articuno', category: 'freeze Pokémon' },
    {entry_no: 145, name_en: 'Zapdos', category: 'electric Pokémon' },
    {entry_no: 146, name_en: 'Moltres', category: 'flame Pokémon' },
    {entry_no: 147, name_en: 'Dratini', category: 'dragon Pokémon' },
    {entry_no: 148, name_en: 'Dragonair', category: 'dragon Pokémon' },
    {entry_no: 149, name_en: 'Dragonite', category: 'dragon Pokémon' },
    {entry_no: 150, name_en: 'Mewtwo', category: 'genetic Pokémon' },
    {entry_no: 151, name_en: 'Mew', category: 'new species Pokémon' },
  ]);
};
     